services:
  mysql_local:
    image: mysql:latest
    container_name: mysql_local
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5

  enset-ebank-discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
  # Config service
  enset-ebank-config-service:
    build: ./config-service
    container_name: config-service
    ports:
      - "9999:9999"
    expose:
      - '9999'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
    environment:
      - DISCOVERY_URL=http://enset-ebank-discovery-service:8761/eureka
      - GITHUB_REPO_URL=https://github.com/YounesJabbour/bank-account-config-repo
      - GITHUB_USERNAME=YounesJabbour
    depends_on:
      enset-ebank-discovery-service:
            condition: service_healthy
  enset-customer-service:
    build: ./customer-service
    container_name: customer-service
    ports:
      - "8081:8081"
    expose:
      - '8081'
    depends_on:
      mysql_local:
        condition: service_healthy
      enset-ebank-discovery-service:
            condition: service_healthy
      enset-ebank-config-service:
            condition: service_healthy
    environment:
      - DISCOVERY_SERVICE_URL=http://enset-ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://enset-ebank-config-service:9999/
      - HOST=mysql_local

  enset-account-service:
    build: ./account-service
    container_name: account-service
    ports:
      - "8082:8082"
    expose:
      - '8082'
    depends_on:
      mysql_local:
        condition: service_healthy
      enset-ebank-discovery-service:
            condition: service_healthy
      enset-ebank-config-service:
            condition: service_healthy
    environment:
      - DISCOVERY_SERVICE_URL=http://enset-ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://enset-ebank-config-service:9999/
      - HOST=mysql_local

  enset-gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    expose:
      - '8080'
    depends_on:
      enset-ebank-discovery-service:
            condition: service_healthy
      enset-ebank-config-service:
            condition: service_healthy
    environment:
      - DISCOVERY_SERVICE_URL=http://enset-ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://enset-ebank-config-service:9999/

volumes:
  db_data:

#  angular_frontend:
#    build: ./angular-front-app
#    container_name: frontend
#    ports:
#      - "4200:80"
#    depends_on:
#      - enset-gateway-service


